[package]
name = "r3st-api"
description = "The r3st S3 API server implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "r3st-api"
path = "src/main.rs"

[dependencies]
r3st-core.workspace = true
