[package]
name = "r3st-conformance"
description = "The r3st conformance test runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "r3st-conformance"
path = "src/main.rs"

[dependencies]
r3st-core.workspace = true
