[package]
name = "r3st-conformance"
description = "The r3st conformance test runner that checks an endpoint against the S3 API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "r3st-conformance"
path = "src/main.rs"

[dependencies]
r3st-core.workspace = true
tokio.workspace = true
reqwest.workspace = true
quick-xml.workspace = true
clap.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
